workflow: add message about autoclosure of the interactive session.
reanahub/reana-client pull request #658
Opened 2023-06-06 13:25 UTC by giuseppe-steduto

When opening an interactive session with the `open` command, the user is now notified about the maximum inactivity time before the session is automatically closed, if the autoclosure was enabled by the REANA administrators.

Closes #657

2023-06-09 12:58 UTC, audrium approved these changes
Looks good!

2023-06-30 09:04 UTC, mdonadoni commented
Works well, good job! 

PS: This PR needs to be rebased

2023-07-03 07:10 UTC, mdonadoni approved these changes

2023-07-04 13:11 UTC, mdonadoni requested changes
There is an issue with this PR when connecting to an older version of REANA (e.g. reana.cern.ch)

```$ reana-client open -w workflow.1
==> SUCCESS: Interactive session opened successfully
https://reana.cern.ch/[...]
It could take several minutes to start the interactive session.
==> ERROR: Interactive session could not be opened: 
'NoneType' object has no attribute 'get'
```

We already had this issue in the past, see: https://github.com/reanahub/reana-client/pull/635. When adding a new field to an endpoint's response specification, bravado sets the field to `None` even if it is not present in the actual JSON response sent by the server. Thus, `reana_info.get("maximum_interactive_session_inactivity_period", {})` returns `None` instead of `{}`.

You should be able to reproduce this by installing the  ~~master~~ latest version from your PRs of reana-client and reana-commons in the same virtualenv.

We have two options:
1) Release a new alpha version of r-commons, bump its version in the `setup.py` of reana-client and fix the issue assuming that "maximum_interactive_session_inactivity_period" is always there
2) Fix the issue so that it works with both the old and the new (future) version of reana-commons

2023-07-11 08:46 UTC, giuseppe-steduto commented
> We have two options:
> 
> 1. Release a new alpha version of r-commons, bump its version in the `setup.py` of reana-client and fix the issue assuming that "maximum_interactive_session_inactivity_period" is always there
> 2. Fix the issue so that it works with both the old and the new (future) version of reana-commons

I went for option 2 since the fix was rather straightforward, as was done in #635, and added a small testcase.

2023-07-12 11:23 UTC, mdonadoni approved these changes
Great, all good now!

2023-07-12 11:33 UTC, merged